<?xml version="1.0"?>

<robot name="flamewheel" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg namespace)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://rotors_description/meshes/flamewheel.dae" />
  <xacro:property name="mass" value="1.14" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.36" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.1" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.013" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.2275" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.045" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.12" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg.m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="838" /> <!-- [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="sqrt2" value="1.4142135623730951" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="0.009" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.018" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor * rotor_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}"
    >
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Create macro for one arm with rotor -->
  <xacro:macro name="arm_with_rotor" params="num dir loc_is_front loc_is_right">
    <xacro:if value="${loc_is_front == 1}">
      <xacro:property name="loc_frontback" value="front" />
      <xacro:property name="col" value="Red" />
    </xacro:if>
    <xacro:unless value="${loc_is_front == 1}">
    <xacro:property name="loc_frontback" value="back" />
      <xacro:property name="col" value="Blue" />
    </xacro:unless>
    <xacro:if value="${loc_is_right == 1}">
      <xacro:property name="loc_leftright" value="right" />
    </xacro:if>
    <xacro:unless value="${loc_is_right == 1}">
      <xacro:property name="loc_leftright" value="left" />
    </xacro:unless>

    <xacro:vertical_rotor
      robot_namespace="${namespace}"
      suffix="${loc_frontback}_${loc_leftright}"
      direction="${dir}"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="${num}"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="${col}"
      use_own_mesh="false"
      mesh="">
      <origin xyz="${loc_is_front * arm_length / sqrt2} ${loc_is_right * arm_length / sqrt2} ${rotor_offset_top}" rpy="0 0 0" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>
  </xacro:macro>

  <xacro:arm_with_rotor num="0" dir="ccw" loc_is_front="1" loc_is_right="1" />
  <xacro:arm_with_rotor num="1" dir="ccw" loc_is_front="-1" loc_is_right="-1" />
  <xacro:arm_with_rotor num="2" dir="cw" loc_is_front="1" loc_is_right="-1" />
  <xacro:arm_with_rotor num="3" dir="cw" loc_is_front="-1" loc_is_right="1" />

</robot>
